language: generic
sudo: required
services:
- docker
script:
- docker build -t therickys93/wikimongodb .
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; docker push therickys93/wikimongodb;
  fi
- sh set_tags.sh
deploy:
  provider: releases
  file_glob: "true"
  skip_cleanup: true
  api_key:
    secure: QXFhjC2LiVekGx0SvR32sMEpD/TPUYCEgLSe3vmAHe4wG2NJKGN2otj3rJZ75eFDfSqL/uJGARtmp6rkH9zqqOdMZRE+wZZjQluNu69hCmk1gkyOqFWPS9o9nk/obvfu1/AzhXKjtGOeogmx3I1VFj+eGUfYZEuXrKb5U3G7qVFd70fhFbF29hp6xi/4YEPYIo5kQUcsYgUPjLL5y5nVd+wL9txJsHlPPu/H5DzhVjqq8T3L0VRDRaRmemi8a9oi6U9FxI+Q2HmwCsSHp0r73JCM6/HCL7wUApqL5WVQ2FCKW+E/JJyMYVxk1yGd9jEh25Sb/pulPB8CGi9ZlRBZoNRQPcFE+tsX8pR5hUJPMQuGHUjQgxfOvf6lrOUtYxd9chu/TpJcY9dyPmUtsKjN2Lk0QP0ChJTMAG2bvuICFT6oRdEm5XUS9UUOO8ndMsP9hAi6rq+2oeSuRgT9YplAAFv/gNiPg1Zfi5O25ZIRAA7S4p7sRkSXO8iw52owvQXArAaF7pYd8V3i+pG7bqohm/zu/txWwj29UYYhynlTw5hy1JM9JpabioYXuWZYQLRMuhJmBOdwFcWLpKAKgyjCxyaZcd+X5u4T4dKUAjmFg/BU3dRLB+QTZY7OCwgbqTURpnWdJKH0JaZwkKFAtrLbMXTJetpR3fQwx5BtaVefq00=
  on:
    branch: master
    repo: therickys93/wikimongodb
